name: CI-CD pipeline to AWS EC2 #Some changes
env:
  REMOTE_USER: "ec2-user"
  S3_BUCKET_NAME: "webbakurdeploy"
  AWS_REGION: "us-east-1"
  REMOTE_HOST: "52.87.234.39"
  
on:
  push:
    branches: 
    - main
jobs:
  ci_pipeline: 
    runs-on: ubuntu-latest
    steps:
      - name: Git clone our repo
        uses: actions/checkout@v1

      - name: AWS autentification
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Copy file to s3
        run: aws s3 cp index.html s3://${{ env.S3_BUCKET_NAME }}
        
  cd_pipeline:
    needs: [ci_pipeline]
    runs-on: ubuntu-latest
    steps:
      - name: Git clone our repo
        uses: actions/checkout@v1
      - name: AWS autentification
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Configure ssh key
        run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      - name: SSH connect to our web server and copy index.html from s3
        run: | 
          ssh -i $HOME/.ssh/key ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }} -o StrictHostKeyChecking=no "sudo su -c 'export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} && export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} && export AWS_DEFAULT_REGION=${{ env.AWS_REGION }} && aws s3 cp s3://${{ env.S3_BUCKET_NAME }}/index.html /var/www/html/'"
 