name: CI-CD pipeline to AWS ASG
env:
  REMOTE_USER: "ubuntu"
  S3_BUCKET_NAME: "webbakurdeploy"
  AWS_REGION: "us-east-1"
  
on:
  push:
    branches: 
    - master
jobs:
  ci_pipeline: 
    runs-on: ubuntu-latest
    steps:
      - name: Git clone our repo
        uses: actions/checkout@v1
      - name: Archive repository
        run: zip -r repo.zip ./index.html
      - name: Archive Appsepc
        run: zip -r repo.zip ./appspec.yml
      - name: AWS autentification
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Copy file to s3
        run: aws s3 cp repo.zip s3://${{ env.S3_BUCKET_NAME }} --recursive:
